# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp sourceCpp
#'@useDynLib SSOSVM
NULL

#'Square Hinge
#'@description THIS FUNCTION DOES
#'@param PARAM1
#'@param PARAM2
#'@return RETURNVAL
#'@examples
#'@export
SquareHinge <- function(YMAT, DIM = 2L, EPSILON = 0.00001, returnAll = FALSE, rho = 1.0) {
    .Call('_SSOSVM_SquareHinge', PACKAGE = 'SSOSVM', YMAT, DIM, EPSILON, returnAll, rho)
}

#'Hinge
#'@description THIS FUNCTION DOES
#'@param PARAM1
#'@param PARAM2
#'@return RETURNVAL
#'@examples
#'@export
Hinge <- function(YMAT, DIM = 2L, EPSILON = 0.00001, returnAll = FALSE, rho = 1.0) {
    .Call('_SSOSVM_Hinge', PACKAGE = 'SSOSVM', YMAT, DIM, EPSILON, returnAll, rho)
}

#'Logistic
#'@description THIS FUNCTION DOES
#'@param PARAM1
#'@param PARAM2
#'@return RETURNVAL
#'@examples
#'@export
Logistic <- function(YMAT, DIM = 2L, EPSILON = 0.00001, returnAll = FALSE, rho = 1.0) {
    .Call('_SSOSVM_Logistic', PACKAGE = 'SSOSVM', YMAT, DIM, EPSILON, returnAll, rho)
}

